ci: Fix test
Some version are skipped

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -101,9 +101,12 @@ jobs:
 
             echo "[TEST] Downloading Runtime Test Mod... [0/3]"
             json="$(curl -s "https://api.github.com/repos/headlesshq/mc-runtime-test/releases/tags/3.0.0" --header "Authorization: ${{ secrets.GITHUB_TOKEN }}")"
-            echo $json
             echo "[TEST] Downloading Runtime Test Mod... [1/3]"
-            url="$(echo $json | jq -r '.assets[].browser_download_url' | grep $i | grep ${{ matrix.loader == 'forge' && 'lexforge' || matrix.loader }})"
+            url="$(echo $json | jq -r '.assets[].browser_download_url' | grep $i | grep ${{ matrix.loader == 'forge' && 'lexforge' || matrix.loader }} || echo "[FAIL]")"
+            [ $url == "[FAIL]" ] && (
+              >&2 echo "[FAIL] There's no Runtime Test Mod for MC $i!";
+              exit 1;
+            )
             echo "[TEST] Downloading Runtime Test Mod... [2/3]"
             curl -Ls -o "mc-runtime-test.jar" $url
             echo "[TEST] Downloading Runtime Test Mod... [3/3]"
