chore: Target 1.21.5

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -102,8 +102,12 @@ jobs:
             echo "[TEST] Downloading Runtime Test Mod... [0/3]"
             json="$(curl -s "https://api.github.com/repos/headlesshq/mc-runtime-test/releases/tags/3.0.0" --header "Authorization: ${{ secrets.GITHUB_TOKEN }}")"
             echo "[TEST] Downloading Runtime Test Mod... [1/3]"
-            url="$(echo $json | jq -r '.assets[].browser_download_url' | grep $i | grep ${{ matrix.loader == 'forge' && 'lexforge' || matrix.loader }} || echo "[FAIL]")"
-            [ $url == "[FAIL]" ] && (
+            # >> FIXME: Workaround since Runtime Test mod for 1.21.5 is not yet released
+            TARGET="$i"
+            [ "$TARGET" = "1.21.5" ] && TARGET="1.21.4"
+            # <<
+            url="$(echo $json | jq -r '.assets[].browser_download_url' | grep $TARGET | grep ${{ matrix.loader == 'forge' && 'lexforge' || matrix.loader }} || echo "[FAIL]")"
+            [ "$url" = "[FAIL]" ] && (
               >&2 echo "[FAIL] There's no Runtime Test Mod for MC $i!";
               exit 1;
             )
